zap:
  level: info
  prefix: '[boost-data]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: true
  retention-day: -1

api_id: 29868054               # 从 https://my.telegram.org/apps 获取
api_hash: "be4dea8d000d41e31794d2c15c13996e" # 从 https://my.telegram.org/apps 获取
phone_number: "+1234567890"  # 你的Telegram账号电话号码
openai_key: "sk-your-openai-key"
min_messages: 20  # 20条消息触发回复
cooldown: 30      # 30分钟冷却时间

message_groups:
  - group_ids:
      - 1234567890  # 群组1 ID (可以是Channel ID或Supergroup ID)
      - 2345678901  # 群组2 ID
    messages:
      - "这是第一条预设消息"
      - "这是第二条预设消息"
      - "这是第三条预设消息"
    interval_ms: 2000    # 每条消息间隔2秒
    daily_schedule:
      - "09:00"          # 每天早上9点发送一轮
      - "14:00"          # 下午2点发送一轮
      - "20:00"         # 晚上8点发送一轮

  - group_ids:
      - 3456789012  # 另一个群组ID
    messages:
      - "这是给其他群组的消息"
      - "这是第二条消息"
    interval_ms: 3000    # 每条消息间隔3秒
    daily_schedule:
      - "10:30"
      - "16:30"


  #149.154.167.50:443
  #-----BEGIN RSA PUBLIC KEY-----
  #MIIBCgKCAQEA6LszBcC1LGzyr992NzE0ieY+BSaOW622Aa9Bd4ZHLl+TuFQ4lo4g
  #5nKaMBwK/BIb9xUfg0Q29/2mgIR6Zr9krM7HjuIcCzFvDtr+L0GQjae9H0pRB2OO
  #62cECs5HKhT5DZ98K33vmWiLowc621dQuwKWSQKjWf50XYFw42h21P2KXUGyp2y/
  #+aEyZ+uVgLLQbRA1dEjSDZ2iGRy12Mk5gpYc397aYp438fsJoHIgJ2lgMv5h7WY9
  #t6N/byY9Nw9p21Og3AoXSL2q/2IJ1WRUhebgAdGVMlV1fkuOQoEzR7EdpqtQD9Cs
  #5+bfo3Nhmcyvk5ftB0WkJ9z6bNZ7yxrP8wIDAQAB
  #-----END RSA PUBLIC KEY-----


  #149.154.167.40:443
  #-----BEGIN RSA PUBLIC KEY-----
  #MIIBCgKCAQEAyMEdY1aR+sCR3ZSJrtztKTKqigvO/vBfqACJLZtS7QMgCGXJ6XIR
  #yy7mx66W0/sOFa7/1mAZtEoIokDP3ShoqF4fVNb6XeqgQfaUHd8wJpDWHcR2OFwv
  #plUUI1PLTktZ9uW2WE23b+ixNwJjJGwBDJPQEQFBE+vfmH0JP503wr5INS1poWg/
  #j25sIWeYPHYeOrFp/eXaqhISP6G+q2IeTaWTXpwZj4LzXq5YOpk4bYEQ6mvRq7D1
  #aHWfYmlEGepfaYR8Q0YqvvhYtMte3ITnuSJs171+GDqpdKcSwHnd6FudwGO4pcCO
  #j4WcDuXc2CTHgH8gFTNhp/Y8/SpDOhvn9QIDAQAB
  #-----END RSA PUBLIC KEY-----